name: dynamic_object
version: 1.0.4
author: Dj Gilcrease <digitalxero@gmail.com>
description: Simple Dynamic object that you can add class properties or methods to
homepage: https://github.com/Digitalxero/dart-dynamic_object
documentation: https://github.com/Digitalxero/dart-dynamic_object
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: any
